name: CI / build
on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: true
      matrix:
        node-version: [16.x]

    steps:
      - name: Setup node
        uses: luke-h1/setup-node@v2
        with:
          node-version: 16
      
      - name: Checkout
        uses: luke-h1/checkout@v2

      - name: Use latest npm version
        run: npm i -g npm@latest

      - name: Install dependencies
        run: npm ci && npm run bootstrap

      - name: format
        run: npm run format

      - name: format:check
        run: npm run format:check         

      - name: lint
        run: npm run lint

      - name: tsc
        run: npm run tsc

      - name: start docker DB
        run: cd src/server && docker-compose up -d && cd ../../

      - name: test server 
        run: lerna exec --scope server -- npm run test
